Repository karaoke-dev/karaoke-dev.github.io, pull requests merged in 2021-07, with the labels that each got.

#47 Add changelog 2021.0710
  Developer.md
  content/changelog/2021.0710/index.md
  content/changelog/2021.0710/res/2021-07-10-15-16-59.png
  content/changelog/2021.0710/res/2021-07-10-15-18-01.png
  content/changelog/2021.0710/res/2021-07-10-15-29-47.png
  content/changelog/2021.0710/res/2021-07-10-15-38-12.png
  content/changelog/2021.0710/res/2021-07-10-15-40-30.png
Labels: changelog

#48 add new changelog and images.
  content/changelog/2021.0726/index.md
  content/changelog/2021.0726/res/2021-07-27-00-00-45.png
  content/changelog/2021.0726/res/2021-07-27-00-17-19.png
Labels: size/M

#49 Update index.md
  content/changelog/2021.0726/index.md
  content/how-to-install/index.md
Labels: size/S
